### ISSUE TITLE
You'll need a new app to open this discord link bug.

### ISSUE THREAD

**Issue by yavko** [gyf304/lpvpn#2]
So today I downloaded the x86_64 version and clicked host just to see what it did when it left a watermark on my screen the I cannot remove even when i click ok. I thought that the app would open discord itself. What I'm saying is to please make a script that checks if discord.exe is running if not to run it. I'll see if I can make a pr.
![image](https://user-images.githubusercontent.com/15178513/106637740-ef759800-6537-11eb-9a34-046bf4be0df9.png)

**Comment by gyf304** [comment]
I think this is caused by the Discord SDK trying to open discord using `discord://` URL scheme, which is not registered on your machine. By default, discord SDK tries to open discord, and crashes if it's not able to. 
I don't think checking if there's a `discord.exe` running is a very good strategy for checking discord availability. And to open discord, one would have to use the `discord://` scheme, which will likely end up with the same prompt.
Instead, I'm going to make the app check if discord is open, and if not just exit (with a warning) without trying to open discord. This should remove the `You'll need a new app to open this discord link` prompt.

**Comment by gyf304** [comment]
mitigated in v1.0.0-beta-2
